### ISSUE TITLE
Find answer article being viewed disappears when logging in and out of form

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#106]
To repro:
1. Visit https://qa.iservicecrm.com/f/customerportal-treeview#/find-answers?topicID=13&articleID=1376
2. Login using top right link

or
1. Login to qa.iservicecrm.com
2. Visit https://qa.iservicecrm.com/f/customerportal-treeview#/find-answers?topicID=13&articleID=1376
3. Logout using top right link

**Comment by jaswantchouhan** [comment]
fixed #106 - http://outdev2.1to1vpn.ddns.net:9015/f/58

**Comment by scottwhitsitt** [comment]
Steve - you should validate this because I don't really understand the issue.

**Comment by sdubrick** [comment]
Appears fixed when using a deep link,  but still happens if just viewing an article normally.  This might be 'good enough' though, @scottwhitsitt what do you think?

**Comment by sdubrick** [comment]
@scottwhitsitt before, see repro steps above for the old issue, which appears fixed.  To repro the other way, just go to http://outdev2.1to1vpn.ddns.net:9015/f/58 then expand any article.  Then either login or logout (article is no longer expanded).  This doesn't seem as bad.. but want you to confirm

**Comment by scottwhitsitt** [comment]
This will become a bigger problem once we add the ability to subscribe to articles. At that point, the user will have an article selected and will see a Login To Subscribe  to this article link. Once they login, the article will be lost and the user will have to do another search to find it.
1. User selects and article to view its contents.
2. User clicks Login and authenticates to the portal.
3. The Selected article must still be selected below.

**Comment by jaswantchouhan** [comment]
issue #106 - fixed now please check on http://outdev2.1to1vpn.ddns.net:9015/f/58#/find-answers

**Comment by scottwhitsitt** [comment]
Tested and confirmed working on outdev2.
