### ISSUE TITLE
My Inbox rows should be clickable

### ISSUE THREAD

**Issue by sdubrick** [OneToOneService/iService-Forms#39]
These rows should function just like the articles in the Find Answers section.  A mouse-over should show any area of the row as clickable (not just the tiny + icon).  Use the Find Articles functionality as a reference point:

**Comment by jaswantchouhan** [comment]
done

**Comment by sdubrick** [comment]
needs to be clickable on all levels of interactions, not just the top level

**Comment by jaswantchouhan** [comment]
done

**Comment by sdubrick** [comment]
This still isn't correct - Please see the Find Answers functionality you did as a reference for how the cursor and clickable area is supposed to function (that one functions perfectly).  
Example -
In the find answers articles, clicking anywhere in the highlighted zone opens and closes the article. This is correct:
![image](https://cloud.githubusercontent.com/assets/5289502/13067488/1a9aadca-d4a3-11e5-9ee2-0bdfd339174c.png)

In the history items, the cursor falsely appears clickable anywhere, but the only place that it actually works if clicked on is in the highlighted zone below.  This is confusing - it should be clickable in the entire row's, just like how find answers does it.  If an area is not clickable it should not falsely just turn into a clickable hand cursor:

The current clickable area:
![image](https://cloud.githubusercontent.com/assets/5289502/13067526/78fb0da6-d4a3-11e5-9c0f-be2a2d393a1e.png)

Another demo of why this is confusing - in the screenshot below, nothing happens when i click, because it's incorrectly indicating that the zone is clickable.  It doesn't actually do anything though - this entire area should actually be active:
![image](https://cloud.githubusercontent.com/assets/5289502/13067545/c3752bc8-d4a3-11e5-83f2-eec90a31b003.png)
